export const REQUEST_CAROUSEL_START = "REQUEST_CAROUSEL_START";
export const REQUEST_CAROUSEL_SUCCESS = "REQUEST_CAROUSEL_SUCCESS";

export const SHOW_LOADER_CAROUSEL_SUCCESS = "SHOW_LOADER_CAROUSEL_SUCCESS";
export const HIDE_LOADER_CAROUSEL_SUCCESS = "HIDE_LOADER_CAROUSEL_SUCCESS";
