export const REQUEST_CARROUSEL_START = "REQUEST_CARROUSEL_START";
export const REQUEST_CARROUSEL_SUCCESS = "REQUEST_CARROUSEL_SUCCESS";

export const SHOW_LOADER_CARROUSEL_SUCCESS = "SHOW_LOADER_CARROUSEL_SUCCESS";
export const HIDE_LOADER_CARROUSEL_SUCCESS = "HIDE_LOADER_CARROUSEL_SUCCESS";
